changed work with tun interface

diff --git a/scripts/init.d/entware-tail b/scripts/init.d/entware-tail
--- a/scripts/init.d/entware-tail
+++ b/scripts/init.d/entware-tail
@@ -7,26 +7,37 @@ fn_start() {
     fi
 
     fn_validate_config || return 1
+    fn_resolve_tun_interface_config || return 1
+    fn_check_tun_interface || return 1
     fn_create_session_if_required || return 1
 
-    fn_acquire_tun_interface || return 1
-    fn_create_running_config
-
+    echo "Starting $NAME service..."
     # usque require root for creating tun interface
     # start-stop-daemon -S -bmc "$USER" -p "$PIDFILE" -x "$USQUE_BIN" -- $(fn_daemon_args) || {
     start-stop-daemon -S -bm -p "$PIDFILE" -x "$USQUE_BIN" -- $(fn_daemon_args) || {
-        echo "Failed to start $NAME service"
-
-        fn_down_tun_interface
-        fn_remove_running_config
+        echo "Failed to start $NAME service" >&2
         rm -f "$PIDFILE"
         return 1
     }
 
-    fn_setup_tun_interface
-    fn_up_tun_interface
+    fn_up_tun_interface || {
+        fn_stop_internal
+        return 1
+    }
 
+    fn_create_running_config
     echo "Started $NAME service"
+}
+
+fn_stop_internal() {
+    echo "Stopping $NAME service..."
+    fn_down_tun_interface
+    fn_remove_running_config
+
+    # kill -15 $(cat "$PIDFILE") && rm -f "$PIDFILE"
+    start-stop-daemon -K -p "$PIDFILE" && rm -f "$PIDFILE"
+
+    echo "Stopped $NAME service"
 }
 
 fn_stop() {
@@ -35,30 +46,7 @@ fn_stop() {
         return 1
     fi
 
-    echo "Stopping $NAME service..."
-    fn_down_tun_interface
-    fn_remove_running_config
-
-    # kill -15 $(cat "$PIDFILE") && rm -f "$PIDFILE"
-    start-stop-daemon -K -p "$PIDFILE" && rm -f "$PIDFILE"
-}
-
-fn_acquire_if() {
-    if fn_is_running; then
-        echo "Cannot perform while service $NAME is running" >&2
-        return 1
-    fi
-
-    fn_acquire_tun_interface
-}
-
-fn_release_if() {
-    if fn_is_running; then
-        echo "Cannot perform while service $NAME is running" >&2
-        return 1
-    fi
-
-    fn_release_tun_interface
+    fn_stop_internal
 }
 
 case "$1" in
@@ -75,13 +63,7 @@ restart)
     fn_stop
     fn_start
     ;;
-acquire-if)
-    fn_acquire_if
-    ;;
-release-if)
-    fn_release_if
-    ;;
 *)
-    echo "Usage: $0 {start|stop|restart|status|acquire-if|release-if}"
+    echo "Usage: $0 {start|stop|restart|status}"
     ;;
 esac
diff --git a/scripts/ipk/postinst b/scripts/ipk/postinst
--- a/scripts/ipk/postinst
+++ b/scripts/ipk/postinst
@@ -1,75 +1,69 @@
 #!/bin/sh
 
 fn_install_binary() {
-  local OPKG_CONF="/opt/etc/opkg.conf"
-  local ARCH=
+    local OPKG_CONF="/opt/etc/opkg.conf"
+    local ARCH=
 
-  if [ -f "$OPKG_CONF" ]; then
-    ARCH=$(cat "$OPKG_CONF" | grep -oE 'mips-3|mips_|mipsel-3|mipsel_|mips64|aarch64-3|aarch64_|armv7|arm_|i386|i686|x86_64' | head -n 1)
-  fi
-  if [ -n "$ARCH" ]; then
-    case "$ARCH" in
-      "mips-3"|"mips_") ARCH="mips" ;;
-      "mipsel-3"|"mipsel_") ARCH="mipsel" ;;
-      "mips64") ARCH="mips64" ;;
-      "aarch64-3"|"aarch64_") ARCH="aarch64" ;;
-      "armv7"|"arm_") ARCH="armv7" ;;
-      "i386"|"i686") ARCH="x86" ;;
-      "x86_64") ARCH="x86_64" ;;
-    esac
-  fi
-
-  if [ -z $ARCH ]; then
-    ARCH=$(uname -m | grep -oE 'mips|mipsel|mips64|aarch64|armv7|i386|i686|x86_64|rlx')
-    if [ "$ARCH" == "rlx" ]; then
-      ARCH="lexra"
-    elif [ "$ARCH" == "mips" ]; then
-      if grep -qE 'system type.*MediaTek' /proc/cpuinfo; then
-        ARCH="mipsel"
-      fi
-    elif [ "$ARCH" == "i386" ] || [ "$ARCH" == "i686" ]; then
-      ARCH="x86"
+    if [ -f "$OPKG_CONF" ]; then
+        ARCH=$(cat "$OPKG_CONF" | grep -oE 'mips-3|mips_|mipsel-3|mipsel_|mips64|aarch64-3|aarch64_|armv7|arm_|i386|i686|x86_64' | head -n 1)
     fi
-  fi
+    if [ -n "$ARCH" ]; then
+        case "$ARCH" in
+        "mips-3" | "mips_") ARCH="mips" ;;
+        "mipsel-3" | "mipsel_") ARCH="mipsel" ;;
+        "mips64") ARCH="mips64" ;;
+        "aarch64-3" | "aarch64_") ARCH="aarch64" ;;
+        "armv7" | "arm_") ARCH="armv7" ;;
+        "i386" | "i686") ARCH="x86" ;;
+        "x86_64") ARCH="x86_64" ;;
+        esac
+    fi
 
-  if [ -z $ARCH ]; then
-    echo "Failed to detect architecture"
-    exit 1
-  fi
+    if [ -z $ARCH ]; then
+        ARCH=$(uname -m | grep -oE 'mips|mipsel|mips64|aarch64|armv7|i386|i686|x86_64|rlx')
+        if [ "$ARCH" == "rlx" ]; then
+            ARCH="lexra"
+        elif [ "$ARCH" == "mips" ]; then
+            if grep -qE 'system type.*MediaTek' /proc/cpuinfo; then
+                ARCH="mipsel"
+            fi
+        elif [ "$ARCH" == "i386" ] || [ "$ARCH" == "i686" ]; then
+            ARCH="x86"
+        fi
+    fi
 
-  echo "Detected arch: $ARCH"
+    if [ -z $ARCH ]; then
+        echo "Failed to detect architecture"
+        exit 1
+    fi
 
-  cp -f "/opt/tmp/usque-keenetic/$ARCH/usque" "$SERVICE_BIN"
-  chmod +x "$SERVICE_BIN"
-  rm -rf "/opt/tmp/usque-keenetic"
+    echo "Detected arch: $ARCH"
+
+    cp -f "/opt/tmp/usque-keenetic/$ARCH/usque" "$SERVICE_BIN"
+    chmod +x "$SERVICE_BIN"
+    rm -rf "/opt/tmp/usque-keenetic"
 }
 
 fn_setup_config() {
-  local USQUE_INSTALL_TYPE="install"
-  if [ -f "$INSTALL_TYPE_FILE" ]; then
-    # Set in preinst script
-    USQUE_INSTALL_TYPE=$(cat "$INSTALL_TYPE_FILE")
-    rm -f "$INSTALL_TYPE_FILE"
-  fi
+    local USQUE_INSTALL_TYPE="install"
+    if [ -f "$INSTALL_TYPE_FILE" ]; then
+        # Set in preinst script
+        USQUE_INSTALL_TYPE=$(cat "$INSTALL_TYPE_FILE")
+        rm -f "$INSTALL_TYPE_FILE"
+    fi
 
-  if [ "$USQUE_INSTALL_TYPE" = "install" ]; then
-    # TODO: Interface + IP
-
-    # # Interface
-    # local DEF_IFACE=$(isp_interface_func)
-    # sed -i -E "s#^ISP_INTERFACE=\".+\"#ISP_INTERFACE=\"$DEF_IFACE\"#" $CONFFILE
-    # echo "Detected ISP interface: $DEF_IFACE"
-    #
-    # # IPv6
-    # local IPV6=$(ipv6_enabled_func "$DEF_IFACE" && echo 1 || echo 0)
-    # sed -i -E "s#^IPV6_ENABLED=([0-9]+)#IPV6_ENABLED=$IPV6#" $CONFFILE
-    # echo "Detected IPv6: $IPV6"
-    #
-    # echo "Current working mode: auto"
-    # echo "You can change settings in the configuration file: $CONFFILE"
-  fi
+    if [ "$USQUE_INSTALL_TYPE" = "install" ]; then
+        # Interface
+        echo "Detect free tun interface..."
+        local iface=$(fn_get_available_tun_interface)
+        if [ $? -eq 1 ]; then
+            echo "Failed to detect tun interface. Set it manually in config file." >&2
+        else
+            sed -i -E "s#^IFACE=\".+\"#IFACE=\"$iface\"#" $CONFIG_FILE
+            echo "Detected tun interface: $iface"
+        fi
+    fi
 }
-
 
 # Stop entware service
 fn_service_stop
diff --git a/scripts/network b/scripts/network
--- a/scripts/network
+++ b/scripts/network
@@ -32,6 +32,17 @@ fn_get_available_ip() {
     return 1
 }
 
+# $1 - interface
+fn_net_if_exists() {
+    ip link show "$1" 2>/dev/null | grep -q "$1"
+}
+
+# $1 - interface
+fn_convert_to_net_if_name() {
+    echo "$1" | tr '[:upper:]' '[:lower:]'
+}
+
+# $1 - interface
 fn_convert_to_ndm_name() {
     echo "$1" | sed 's/^opkg/Opkg/; s/tun/Tun/'
 }
@@ -68,12 +79,6 @@ fn_ndm_if_set_address() {
     fn_ndm_cmd \
         "interface $1 ip address $2 $3" \
         "Failed to set ip/netmask for interface $1"
-    # local out
-    # out=$(/bin/ndmc -c "interface $1 ip address $2 $3" 2>&1 >/dev/null) || {
-    #     echo "Failed to set ip/netmask for interface $1:"
-    #     echo "| $out" >&2
-    #     return 1
-    # }
 }
 
 # $1 - ndm interface
@@ -109,37 +114,30 @@ fn_ndm_save_system_config() {
         "Failed to save system config"
 }
 
-fn_load_tun_interface_config() {
-    if [ -z "$IFACE" ]; then
-        if [ -n "$RESERVED_IFACE" ]; then
-            IFACE="$RESERVED_IFACE"
-        else
-            IFACE=$(fn_get_available_tun_interface)
-        fi
-    fi
-
+fn_resolve_tun_interface_config() {
     if [ -z "$IFACE_IP" ]; then
-        if [ -n "$RESERVED_IFACE_IP" ]; then
-            IFACE_IP="$RESERVED_IFACE_IP"
-        else
-            IFACE_IP=$(fn_get_available_ip)
+        local val=$(fn_get_available_ip)
+        if [ $? -eq 1 ]; then
+            echo "Failed to get dynamic ip address for interface $IFACE" >&2
+            return 1
         fi
+        IFACE_IP="$val"
     fi
 
     if [ -z "$IFACE_MASK" ]; then
-        if [ -n "$RESERVED_IFACE_MASK" ]; then
-            IFACE_MASK="$RESERVED_IFACE_MASK"
-        else
-            IFACE_MASK="255.255.255.255"
-        fi
+        IFACE_MASK="255.255.255.255"
     fi
 
     if [ -z "$IFACE_NAME" ]; then
-        if [ -n "$RESERVED_IFACE_NAME" ]; then
-            IFACE_NAME="$RESERVED_IFACE_NAME"
-        else
-            IFACE_NAME="usque"
-        fi
+        IFACE_NAME="usque"
+    fi
+}
+
+fn_check_tun_interface() {
+    local iface=$(fn_convert_to_net_if_name)
+    if fn_net_if_exists "$iface"; then
+        echo "Interface $IFACE is already in use." >&2
+        return 1
     fi
 }
 
@@ -147,19 +145,28 @@ fn_create_tun_interface() {
     echo "Create tun interface $IFACE: $IFACE_IP $IFACE_MASK"
     local iface=$(fn_convert_to_ndm_name "$IFACE")
 
-    if fn_ndm_if_exists "$iface"; then
-        fn_ndm_if_remove "$iface"
-    fi
-
     fn_ndm_if_create "$iface" || return 1
-    fn_setup_tun_interface || return 1
-
-    # fn_ndm_if_up "$iface"
-    # fn_ndm_save_system_config
+    fn_ndm_save_system_config
 }
 
-fn_setup_tun_interface() {
+fn_remove_tun_interface() {
+    echo "Remove tun interface $IFACE"
     local iface=$(fn_convert_to_ndm_name "$IFACE")
+
+    # fn_ndm_if_down "$iface"
+    fn_ndm_if_remove "$iface" || return 1
+    fn_ndm_save_system_config
+}
+
+fn_up_tun_interface() {
+    local iface=$(fn_convert_to_ndm_name "$IFACE")
+
+    if ! fn_ndm_if_exists "$iface"; then
+        echo "Create tun interface $IFACE"
+        fn_ndm_if_create "$iface" || return 1
+    fi
+
+    echo "Setup tun interface $IFACE ($IFACE_NAME): ip=$IFACE_IP netmask=$IFACE_MASK"
     fn_ndm_if_set_description "$iface" "$IFACE_NAME" || return 1
 
     fn_ndm_cmd \
@@ -175,98 +182,15 @@ fn_setup_tun_interface() {
     fn_ndm_cmd \
         "interface $iface ip mtu 1280" \
         "Failed to set MTU" || return 1
-}
 
-fn_remove_tun_interface() {
-    echo "Remove tun interface $RESERVED_IFACE"
-    local iface=$(fn_convert_to_ndm_name "$RESERVED_IFACE")
-
-    # fn_ndm_if_down "$iface"
-    fn_ndm_if_remove "$iface"
-    # fn_ndm_save_system_config
-}
-
-fn_up_tun_interface() {
-    if [ -z "$RESERVED_IFACE" ]; then
-        echo "No reserved interface to work with"
-        return 1
-    fi
-
-    echo "Up tun interface $RESERVED_IFACE"
-    local iface=$(fn_convert_to_ndm_name "$RESERVED_IFACE")
-
-    fn_ndm_if_up "$iface"
-    # fn_ndm_save_system_config
+    fn_ndm_if_up "$iface" || return 1
 }
 
 fn_down_tun_interface() {
-    if [ -z "$RESERVED_IFACE" ]; then
-        echo "No reserved interface to work with"
+    if [ -z "$IFACE" ]; then
+        echo "No interface to work with" >&2
         return 1
     fi
-
-    echo "Down tun interface $RESERVED_IFACE"
-    local iface=$(fn_convert_to_ndm_name "$RESERVED_IFACE")
 
     fn_ndm_if_down "$iface"
-    # fn_ndm_save_system_config
-}
-
-fn_acquire_tun_interface() {
-    echo "Resolve interface credentials..."
-    fn_load_tun_interface_config || return 1
-
-    local changed=0
-
-    if [ "$IFACE" != "$RESERVED_IFACE" ]; then
-        if [ -n "$RESERVED_IFACE" ]; then
-            echo "Acquired interface $RESERVED_IFACE changed to $IFACE"
-            echo "Remove old acquired interface $RESERVED_IFACE"
-            local reserved_iface=$(fn_convert_to_ndm_name "$RESERVED_IFACE")
-            fn_ndm_if_remove "$reserved_iface"
-        fi
-
-        # create new interface
-        fn_create_tun_interface || return 1
-        changed=1
-    else
-        local iface=$(fn_convert_to_ndm_name "$IFACE")
-
-        if [ -n "$RESERVED_IFACE_IP" ] && [ "$IFACE_IP" != "$RESERVED_IFACE_IP" ]; then
-            echo "IP address $RESERVED_IFACE_IP changed to $IFACE_IP"
-            changed=1
-        fi
-
-        if [ -n "$RESERVED_IFACE_MASK" ] && [ "$IFACE_MASK" != "$RESERVED_IFACE_MASK" ]; then
-            echo "Netmask $RESERVED_IFACE_MASK changed to $IFACE_MASK"
-            changed=1
-        fi
-
-        if [ -n "$RESERVED_IFACE_NAME" ] && [ "$IFACE_NAME" != "$RESERVED_IFACE_NAME" ]; then
-            echo "Interface name $RESERVED_IFACE_NAME changed to $IFACE_NAME"
-            fn_ndm_if_set_description "$iface" "$IFACE_NAME"
-            changed=1
-        fi
-
-        if [ "$changed" -eq 1 ]; then
-            fn_ndm_if_set_address "$iface" "$IFACE_IP" "$IFACE_MASK" || return 1
-        fi
-    fi
-
-    if [ "$changed" -eq 1 ]; then
-        RESERVED_IFACE="$IFACE"
-        fn_create_reserved_config
-        fn_ndm_save_system_config
-    fi
-}
-
-fn_release_tun_interface() {
-    if [ -z "$RESERVED_IFACE" ]; then
-        echo "No reserved interface to work with"
-        return 1
-    fi
-
-    fn_remove_tun_interface
-    fn_remove_reserved_config
-    fn_ndm_save_system_config
 }
